### ISSUE TITLE
Structured Concurrency

### ISSUE THREAD

**Issue by PaulWoitaschek** [adrianolc/droid-app-builder#41]
Hey Adriano!

Interesting project you created here. Just a few things I noticed:

https://github.com/adrianolc/droid-app-builder/blob/688b999ff090424810a259a8a5ba5472d3dd715f/core-domain/src/main/java/adrianolc/appbuilder/domain/use_case/branch/GetBranchUseCase.kt#L15-L19

This code has two fundamental flaws.
First of all, the `getBranch` function is already suspending. It should be the responsibility of the method you call to ensure that it is running on the correct dispatcher.
As the function is already suspending, usually adding a `withContext(...)` does not have any effect.

The other problem is `executeToResult`.
This is a generic try-catch. The main problem here is, that it breaks [Structured Concurrency](https://kotlinlang.org/docs/coroutines-basics.html) by catching `CancellationException`s. This will eventually lead to an unpredictable application state.

Besides that, I would recommend to not add a generic try-catch but instead catch specific exceptions and handle them gracefully.

Also there seem to be a few empty classes hanging around, which could be removed
https://github.com/adrianolc/droid-app-builder/blob/master/feature-branches/impl/src/test/java/adrianolc/appbuilder/feature_repo/impl/domain/use_case/LoadBranchesUseCaseTest.kt

**Comment by adrianolc** [comment]
Hi @PaulWoitaschek, 

Many thanks for your review. Yes, this part of the code is kind of old (2 years ago) I just moved to the new module 😄 

I was reviewing last month this project and had this on my ToDo, to remove the context switch completely from here. I use this project to study so whenever I have time and a new thing that I want to try I come over here and break everything. The last thing that I did was better modularization and convention plugins.

Even being a study project that I do alone, I like to open PRs here so I can have a better view and scope of changes that I'm doing, you can check old PRs here https://github.com/adrianolc/droid-app-builder/pulls?page=1&q=is%3Apr

Again, many thanks to come over here and add your thoughts, appreciated!!

**Comment by PaulWoitaschek** [comment]
Totally makes sense! Looking forward to get to know you 🎉
